parameters:
- name: mySteplist
  type: stepList
  default:
    - script: echo step one
    - script: echo step two

trigger:
- master

jobs:
- job: myJob
  pool:
    name: own-agent-pool
  steps:
  - bash: touch santhoshpskfile.txt && pwd
- job: myJob1
  pool:
    name: own-agent-pool
  steps:
  - bash: ls -l && pwd
  dependsOn: [myJob]