trigger: none

jobs:
- job: myJob
  pool:
    name: ubuntu-22.04
  steps:
  - bash: touch santhoshpskfile.txt && pwd
- job: myJob1
  pool:
    name: ubuntu-22.04
  steps:
  - bash: ls -l && pwd
  dependsOn: [myJob]