trigger: none

jobs:
- job: myJob
  pool:
    vmImage: ubuntu-latest
  steps:
  - bash: touch santhoshpskfile.txt && pwd
- job: myJob1
  pool:
    vmImage: ubuntu-latest
  steps:
  - bash: ls -l && pwd
  dependsOn: [myJob]