trigger: none

pool:
    vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build the App
  jobs:
  - job: BuildJob
    displayName: Building the App
    steps:
    - task: Maven@4
      displayName: Maven package
      inputs:
        mavenPOMFile: pom.xml
        goals: package verify
        #options: -DskipTests
    - task: PublishBuildArtifacts@1
      displayName: Uploading war file
      inputs:
        PathtoPublish: 'target/vprofile-v2.war'
        ArtifactName: 'vprofile'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        reportDirectory: 'target/site/jacoco/'