parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

trigger:
- master

jobs:
- job: myJob
  pool:
    name: own-agent-pool
  steps:
  - bash: touch santhoshpskfile.txt && pwd
- job: myJob1
  pool:
    name: own-agent-pool
  steps:
  - bash: ls -l && pwd
  dependsOn: [myJob]