trigger: none

pool:
    vmImage: ubuntu-latest

steps:
- task: Maven@4
  displayName: Unit Test
  inputs:
    mavenPOMFile: pom.xml
    goals: test
- task: Maven@4
  displayName: Code Coverage
  inputs:
    mavenPOMFile: pom.xml
    goals: verify
    options: -DskipUnitTests
- task: PublishCodeCoverageResults@2
  displayName: Upload Code Coverage Result
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: 'target/site/jacoco/jacoco.xml'
- task: Maven@4
  displayName: Building the App
  inputs:
    mavenPOMFile: pom.xml
    goals: package
    options: -DskipTests
- task: PublishBuildArtifacts@1
  displayName: Uploading war file
  inputs:
    PathtoPublish: 'target/vprofile-v2.war'
    ArtifactName: 'vprofile'
